 - name: Say hello from play level
   hosts: all
   connection: local
   vars:
     - URL: vars.playlevel.com
     - URL1: vars.playlevel1.com
     - URL2: vars.playlevel2.com
     - URL3: Vars.playlevel3.com
     - x: nagababu
     - y: nalluri
   tasks:
     - name: Task level hello
       ansible.builtin.debug:
         msg:
         - URL = {{URL}}
         - URL1 = {{URL1}}
         - URL2 = {{URL2}}
         - URL3 = {{URL3}}
         - "{{x,y}}"

 - name: Declare variable from files
   hosts: all
   connection: local
   vars_files:
     - file2.yml
   tasks:
     - name: access variable from files
       ansible.builtin.debug:
         msg: Facebook URL = {{facebook,father,mother,brother,wife,daughter,myself}}

 - name: Variable from inventory
   hosts: all
   connection: local
   tasks:
     - name: accessing variable from inventory file
       ansible.builtin.debug:
         msg: url = {{url1}}


 - name: access facts
   hosts: all
   connection: local
   tasks:
     - name: Get access facts
       ansible.builtin.debug:
         msg: ansible host name = {{ansible_fqdn}}


 - name: Storing output in one variable
   hosts: all
   connection: local
   tasks:
     -  name: register a variable
        ansible.builtin.shell: uptime
        register: out

     - name: store output
       ansible.builtin.debug:
         msg: "{{out}}"



