 - name: Say hello from play level
   hosts: all
   connection: local
   vars:
     - URL: vars.playlevel.com
     - URL1: vars.playlevel1.com
     - URL2: vars.playlevel2.com
     - URL3: Vars.playlevel3.com
     - x: nagababu
     - y: nalluri
   tasks:
     - name: Task level hello
       ansible.builtin.debug:
         msg:
         - URL = {{URL}}
         - URL1 = {{URL1}}
         - URL2 = {{URL2}}
         - URL3 = {{URL3}}
         - "{{x,y}}"
