 - name: Say hello from play level
   hosts: all
   connection: local
   vars:
     URL: vars.playlevel.com
   task:
     - name: Task level hello
       ansible.builtin.debug:
         msg: URL = {{URL}}
