- name: Learning
  hosts: all
  tasks:
    - name: Printing My name
      ansible.builtin.debug:
       msg: My name is nagababu nalluri

    - name: Using shell
      ansible.builtin.shell:
      - touch file7 file8
      - mkdir nagababu
      - mkdir lalitha
