 - name: Declaring variables from play leve
   hosts: all
   connection: local
   vars:
    url: palylevel.example.com
   tasks:
      - name: accessing variables from playlevel
        ansible.builtin.debug:
         msg: url == {{url}}

      - name: Print my name
        ansible.builtin.debug:
          msg:
           - This is Nagababu Nalluri from vijayawada
           - I have completed my graduation in B.tech specelization ece

      - name: Printing a value
            ansible.builtin.debug:
              msg: a value is {{a}}
              when: a=10