 - name: Declaring variables from play leve
   hosts: all
   connection: local
   vars:
    - url: palylevel.example.com
    - a: 10

   vars_files:
     - files.yml
     - file2.yml
   tasks:
      - name: accessing variables from playlevel
        ansible.builtin.debug:
         msg: url == {{url}}

      - name: Print my name
        ansible.builtin.debug:
          msg:
           - This is Nagababu Nalluri from vijayawada
           - I have completed my graduation in B.tech specelization ece

      - name: Printing a value
        ansible.builtin.debug:
              msg: a value is {{a}}

      - name: accessing variable from files.yml
        ansible.builtin.debug:
          msg:
          - url == {{a}}
          - url == {{b}}
          - url == {{c}}
          - url == {{d}}
          - url == {{facebook}}
 - name: access variable from inventory file
   hosts: all
   connection: local
   tasks:
      - name: variable from inventory
        ansible.builtin.debug:
          msg: url1 == {{url1}}