 - name: Declaring variables from play leve
   hosts: all
   connection: local
   vars:
    url: palylevel.example.com
   tasks:
      - name: accessing variables from playlevel
        ansible.builtin.debug:
         msg: url == {{url}}